# 2. Javascript action | using: 'node'
# https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-javascript-action
name: 'Deploy to AWS S3'
description: 'Deploy a static website via S3.'
inputs:
  bucket:
    description: 'The S3 bucket name.'
    required: true
  bucket-region:
    description: 'The region of the S3 bucket.'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder containing the deployable files.'
    required: true
runs:
  using: 'node16'
  main: 'main.js'