name: Deployment
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      # using custom composite reusable action with input
      - name: Load & cache dependencies
        id: cache-deps
        uses: ./.github/actions/cached-deps
        with:
          caching: 'false'
      # showing custom composite reusable action output
      - name: Output information
        run: echo "Cache used? - ${{ steps.cache-deps.outputs.used-cache }}"
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      # using custom composite reusable action
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      # using custom composite reusable action
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
      - name: Build website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
      # using custom javascript reusable action with input & output
      - name: Deploy site by Javascript action
        id: deploy-site-via-js-action
        uses: ./.github/actions/deploy-s3-javascript
        env:
          AWS_ACCESS_KEY_ID: AAAAAAAAA
          AWS_SECRET_ACCESS_KEY: BBBBBBBBB
        with:
          bucket: aws-custom-bucket-name
          dist-folder: ./dist
      # display custom javascript reusable action output
      - name: Output Javascript action information
        run: |
          echo "Live URL: ${{ steps.deploy-site-via-js-action.outputs.website-url }}"
      # using custom Docker container action reusable action with input & output
      - name: Deploy site by Docker container action
        id: deploy-site-via-docker-action
        uses: ./.github/actions/deploy-s3-docker
        env:
          AWS_ACCESS_KEY_ID: AAAAAAAAA
          AWS_SECRET_ACCESS_KEY: BBBBBBBBB
        with:
          bucket: aws-custom-bucket-name
          dist-folder: ./dist
      # display custom Docker container reusable action output
      - name: Output Docker container action information
        run: |
          echo "Live URL: ${{ steps.deploy-site-via-docker-action.outputs.website-url }}"